name: Update ICS

on:
  schedule:
    - cron: "0 * * * *"   # 每小时跑一次
  workflow_dispatch:      # 手动触发
  push:
    paths:
      - scrape_to_ics.py
      - requirements.txt
      - .github/workflows/update-ics.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run scraper
        env:
          COOKIES: ${{ secrets.COOKIES }}   # 稍后在仓库里添加这个 Secret
        run: python scrape_to_ics.py
      - name: Commit artifact
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add schedule.ics
            git commit -m "Update schedule.ics"
            git push
          else
            echo "No changes."
          fi
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
